### ISSUE TITLE
Metadata Editor Issue - Nodes blank

### ISSUE THREAD

**Issue by bajonal** [iobis/obis-issues#100]
When I log into Metadata Editor under Nodes, there is nothing on my screen except the word Nodes.

**Comment by JohnNichollsTCD** [comment]
I concur. Same problem - Also there is no "Institutions" list. Is this a "membership" issue?

**Comment by pieterprovoost** [comment]
No issues here with your credentials, can you please try a [refresh](https://refreshyourcache.com/en/cache/) and if not let me know your OS and browser versions?

**Comment by bajonal** [comment]
No institutes either and under Activities no Nodes in Node filter drop down.  Have refreshed several times...
Google Chrome is up to date Version 70.0.3538.102 (Official Build) (64-bit)
Mac OS High Sierra Version 10.13.6

**Comment by pieterprovoost** [comment]
Please try again. For OTN and OPI the institutes list will be empty as no datasets are linked to these nodes, but it should be possible to edit the node info.

**Comment by bajonal** [comment]
Looks like I will be able to edit OTN OBIS Node, but wanted to mention there are now two OTN OBIS nodes the other is called Ocean Tracking Network OBIS...should remove one of these.
