### ISSUE TITLE
taxa search not working intermittently?

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/obis-issues#114]
Reported by OBIS Australia.

**Comment by cperaltab** [comment]
Hi! I have being testing few searches and I saw that the names box doesen't autocomplete and only respond to searching once you press enter. Clicking over the green button doesn't work for me.

**Comment by cperaltab** [comment]
The other thing is that few names in Spanish are not registered therefore searching by common names in Spanish is not possible for some species. Maybe this could happen for other languages. For example: Lionfish=Pez leon, and I can't search by "Pez leon".

**Comment by pieterprovoost** [comment]
It should autocomplete, can you please let me know which browser and browser version you are using? Thanks.

**Comment by cperaltab** [comment]
Oh! I'm using Mozzilla Firefox, the last version

**Comment by pieterprovoost** [comment]
Common names are taken from WoRMS, maybe @bart-v can help?

**Comment by cperaltab** [comment]
But I just tried in Google Chrome and doesn't work either...

**Comment by bart-v** [comment]
A few points:
- Lionfish is used for several species. It's not much use to rely on a common name: better to use the scientific name
- WoRMS has never focused on common names, we only have a limited number of in the system. This is especially true for non-English languages
- for fish, we could improve the common name coverage by synchronizing them from FishBase (source of fish species names in WoRMS)

I guess this deserves a separate issue (but only if it's really important)

**Comment by pieterprovoost** [comment]
@cperaltab Which search term are you using for which search type? Maybe there are no results?

![ezgif-3-4fb020ee4854](https://user-images.githubusercontent.com/490041/52059214-82565300-2569-11e9-9f92-19acb89254c8.gif)

**Comment by diodon** [comment]
Is your Internet very slow? (sorry I already know the answer) It is working for me.

**Comment by pieterprovoost** [comment]
I added a fix so the dropdown clearly shows which item is active (either by using the mouse or by using the arrow keys). Please reopen if there still is an issue.

<img width="486" alt="Screenshot 2019-05-23 at 10 17 20" src="https://user-images.githubusercontent.com/490041/58236798-f8aed900-7d43-11e9-8349-3f1b771820f8.png">
