### ISSUE TITLE
OBIS result page: difference between occurrence records and QCed records

### ISSUE THREAD

**Issue by diodon** [iobis/obis-issues#133]
I'm looking at the [lionfish results page](https://obis.org/taxon/159559) and I see that there is 2.463 records but when you mouse over the data quality items (e.g. dropped records) you see something like 33 of 19.166 records. Where this 19K records came from? Is that an error?

![image](https://user-images.githubusercontent.com/2551823/53921506-c38bd680-40c4-11e9-9f7e-72bedbc105bb.png)

**Comment by pieterprovoost** [comment]
Thanks @diodon 19,166 is the total number of records including absence records and dropped records. The number of absence records was not displayed on the taxon page, but that has been fixes. It now says 2,463 occurrence records, 16,670 absence records, and 33 dropped records. The QC panel expresses problems as a fraction of the total number of records, which is 2,463 + 16,670 + 33 = 19,166 records.
