### ISSUE TITLE
API issue: Name not found error even though name is accepted in WoRMS

### ISSUE THREAD

**Issue by albenson-usgs** [iobis/obis-issues#134]
API is returning error: "Name not found" even though the scientific name is an accepted one in WoRMS. Maybe the species has no records in OBIS? If so, error should more clearly state that.

https://api.obis.org/Statistics/years?scientificname=Ancistrum%20cyclidioides&areaid=274

http://www.marinespecies.org/rest/AphiaRecordByAphiaID/394834

**Comment by pieterprovoost** [comment]
Duplicate of https://github.com/iobis/obis-issues/issues/136
