### ISSUE TITLE
API issue: Strange error "Cannot read property 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by albenson-usgs** [iobis/obis-issues#135]
I'm not sure what this error is about.

https://api.obis.org/Statistics/years?scientificname=Balanus%20amphitrite&areaid=274
https://api.obis.org/v3/occurrence?scientificname=Balanus%20amphitrite&areaid=274%22
https://api.obis.org/v3/occurrence?scientificname=Balanus%20eburneus&areaid=274

**Comment by pieterprovoost** [comment]
Changed error message to `taxon has no rank` and synced all Balanus species with WoRMS to fix the issue. Please reopen if this happens again.

To fix the second request remove the trailing quotes character.
