### ISSUE TITLE
mapper.iobis.org not redirected

### ISSUE THREAD

**Issue by bart-v** [iobis/obis-issues#146]
Better to redirect this to https://mapper.obis.org/ ?

**Comment by pieterprovoost** [comment]
@bart-v Can you please change DNS for mapper.iobis.org to 178.62.184.244?

**Comment by bart-v** [comment]
done

**Comment by pieterprovoost** [comment]
@bart-v My previous request was incorrect, can you please changed that IP to 146.185.135.41?

Cheers

**Comment by bart-v** [comment]
done
