### ISSUE TITLE
Is it possible for me to update and change the COTT mailing list? 

### ISSUE THREAD

**Issue by JohnNichollsTCD** [iobis/obis-issues#155]
Who should I approach in order to add/remove members from the OBIS Communication and Outreach Task Team list, or can I do it myself? I don't believe I have admin rights, and I appreciate the need to restrict this level of access for security and DP.

**Comment by wardappeltans** [comment]
Changing members to a group in oceanexpert is only possible by admins. You can send updates by email to me.
