### ISSUE TITLE
Use of basisOfRecord for IFCB data

### ISSUE THREAD

**Issue by AbbyBenson** [iobis/obis-issues#171]
Based on discussions yesterday with my working group on basisOfRecord it seems like we may need some discussion within in the OBIS network on the best way to handle basisOfRecord and identifiedBy for IFCB data. Stace Beaulieu with WHOI had originally decided to use basisOfRecord = MachineObservation for records that are identified by a computer and basisOfRecord = HumanObservation for those that are identified by a person back in a lab. She has written this into documents with NASA SeaBASS. After our discussion yesterday, Stace did some digging into how the OBIS network is currently handling basisOfRecord for this type of data and these are her findings:

First finding: is that there are barely any datasets in OBIS that appear to derive from imagery.
Main finding: is that there is no consistency in the use of basisOfRecord in OBIS. The single dataset in OBIS that derived from IFCB used basisOfRecord MachineObservation and did not use identifiedBy. For this single dataset it so happens that the classification was by machine. Two other datasets deriving from imagery populated basisOfRecord with the word Occurrence. One dataset for zooplankton examined under a microscope for which I would have used PreservedSpecimen instead used HumanObservation.
IFCB:
https://obis.org/dataset/a326b7a3-1e74-4ae9-95d4-6b38d889cbe9
http://ipt.vliz.be/eurobis/resource?r=phytoplankton-jerico-ifcb
I have to assume automated classification based on abstract. They used basisOfRecord MachineObservation and did not use identifiedBy. They sometimes populated identificationQualifier with NK or CPX, but I don’t know what that means.
Zooscan:
Paper saying data obtained from Zooscan: https://doi.org/10.1002/gdj3.68
But I can’t tell in the OBIS dataset that the data derived from Zooscan with automated classification: https://obis.org/dataset/afa5b0e8-826d-4433-b698-beb176ef7880
For basisOfRecord they put the word Occurrence. They did not use identifiedBy nor identificationQualifier.
ROV survey: (we had discussed analyzing video imagery as basisOfRecord MachineObservation, and then the need to use identifiedBy for human or machine as for IFCB and other plankton imaging systems)
Here’s an example that says “Surveys were typically undertaken using one or more of the following techniques, remotely operated video (ROV), drop-down or towed video, grab sampling, core sampling, clump sampling, diver video, MNCR phase 2 diver recording, and intertidal transects and quadrats.” https://obis.org/dataset/ebe7ffad-b134-40d3-b3df-21b675c4bcb1
I expect to see a variety of basisOfRecord; however, for basisOfRecord they put the word Occurrence. They did not use identifiedBy nor identificationQualifier.
Zooplankton under microscope:
https://obis.org/dataset/bff60a89-23bb-4f31-9b40-7bbf2bb19b77
http://ogc-act.csiro.au/ipt/resource?r=anmn_nrs_bgc_plankton_zooplankton_data
(abstract mentions Zooscan but the data do not derive from Zooscan)
These appear to be net samples preserved in formalin. They used basisOfRecord HumanObservation but I think I would have used PreservedSpecimen. They did not use identifiedBy nor identificationQualifier.
Conclusion: At this time I will proceed with recommendation to IFCB data providers to use basisOfRecord MachineObservation vs HumanObservation to distinguish classifications made by machine vs human. I will add a caveat to my datasets, and to the recommendations to NASA SeaBASS, that recommendations for the use of Darwin Core basisOfRecord and identifedBy may change as they are under consideration in the OBIS Network collaboration with the EU project JERICO-S3 to describe best practices and develop standardized protocols for data management of biological imagery data.

**Comment by pieterprovoost** [comment]
Adding @LennertSchepers.

**Comment by LennertSchepers** [comment]
Dear @albenson-usgs 

This is really helpful for us! Thanks! Indeed, we will collect and describe best practices in the framework of the Jerico-S3 project. Once we have these best practices, we will also make sure our own datasets follow these guidelines, such as the LifeWatch VLIZ zooplankton datasets linked to https://doi.org/10.1002/gdj3.68

FYI: our zooscan plankton sample identifications are aided by the Plankton Identifier, but 

> All ROIs predicted by Plankton Identifier will be validated twice: initially by non‐taxonomist, ultimately by an expert on a yearly basis. 

@jonasmortelmansvliz can help for detailed questions.

**Comment by skybristol** [comment]
Wow! This is awesome! Thanks to Stace for digging through to put it together and to @albenson-usgs for laying it out as an issue. In addition to providing a great use case for how IFCB data should be documented and encoded, Stace also lays out what could be the start to an interesting inference algorithm that could be used to suggest values for the basisOfRecord and other attributes. These could be applied in the data processing pipeline to introduce algorithm-generated fields and added as additional filters for use, with some degree of uncertainty, of course. Users could choose to trust the filters or not, and results might help inform upstream data management practices.

**Comment by PatriciaCabrera** [comment]
As mentioned by @LennertSchepers  above, we are looking into recommendations and best practices for data management of plankton imaging systems. Thank you for this great discussion and resource.

According to obis, humanObservation: should be used for sightings of specimens. Specimens that were observed and again released (which is not the case for plankton image sensors); and machineObservation: For data from sensors (tracked or tagged specimens, c-pods,). Specimens identified by machines (e.g. image recognition and DNA sequencing). 

Having this in account, we are interpreting that basisOfRecord should be always machineObservation for image datasets derived from imaging systems (e.g; Cytosense, IFCB, UVP, CPICS, etc). Then, if the identification has been verified by a person, this can be added in IdentifiedBy, that ideally should be a mandatory field for image datasets (now its not as per OBIS). 

We are also looking into identificationVerificationStatus, identificationReferences and previousIdentifications to give more details about the identification process, but this can be another topic of discussion. 

These are our first thoughts after digging into DwC documentation. 

Does this sound reasonable @pieterprovoost  @albenson-usgs @rubenpp7

**Comment by sbeaulieu** [comment]
I am in agreement with this recommendation by @PatriciaCabrera for plankton imaging systems to use basisOfRecord MachineObservation and require the use of identifiedBy https://dwc.tdwg.org/terms/#dwc:identifiedBy with the expansion of the term definition "people, groups, or organizations who assigned the Taxon to the subject" to include automated classification software. The 'downside' to this is that I think it will be more difficult for the end user to quickly determine that an identification was made by a machine, but an 'upside' is that some provenance may be provided e.g., if the specific auto-classification algorithm/implementation/version is given in the identifiedBy. I will communicate this to my colleagues at NASA SeaBASS and EDI.

**Comment by AbbyBenson** [comment]
I think the final recommendation for this is documented [here](https://repository.oceanbestpractices.org/handle/11329/1917) and so I'm closing this ticket.
