### ISSUE TITLE
Update extended measurement or fact extension to follow existing dwciri namespace

### ISSUE THREAD

**Issue by AbbyBenson** [iobis/obis-issues#196]
When the [extended measurement or fact extension](https://tools.gbif.org/dwca-validator/extension.do?id=http://rs.iobis.org/obis/terms/ExtendedMeasurementOrFact) was created the working group that created it was unaware of the [dwciri namespace](https://dwc.tdwg.org/terms/#usewithiri) and created the terms `measurementTypeID`, `measurementUnitID`, `measurementValueID`. These are redundant to `dwciri:measurementType`, `dwciri:measurementUnit`, and `dwciri:measurementValue`, respectively. In order to be in line with the existing standard, the extended measurement or fact extension needs to have a name change put in place for those three terms.

**Comment by tucotuco** [comment]
I am in the process of creating updated Core and Extension files already, and anticipate being able to create them from scripts. If you want, I would be happy to take this one on as well.

**Comment by tucotuco** [comment]
The new [script](https://github.com/tdwg/dwc/blob/master/build/build_extension.py) makes it so easy to make extension files that I could not resist. I [made one for eMoF](https://gist.github.com/tucotuco/ba0bacfa6e3b58eed07bff0e74da2d0c) based  on the extension that is in production, changing the three non-DwC ID terms to their dwciri equivalents. 

This new extension XML file relies on the adoption of the new extension.xsd schema, which I have provided to GBIF [here](https://github.com/gbif/rs.gbif.org/pull/71). That update allows the usage comments to be included in the XML file separate from the term definition and examples - mirroring the way these are managed in the Darwin Core standard.

While working on this it reminded me of a proposal for a new term, [parentMeasurementID](https://github.com/tdwg/dwc/issues/362) that would  be immensely useful to include in this extension. I recommended reviewing that term and adding the OBIS perspective or support if deemed meritorious.

**Comment by pieterprovoost** [comment]
Does anyone know if this would work with IPT? As far as I know there's no indication of namespace in the mapping panel?

**Comment by bart-v** [comment]
It's maybe a nice theoretical approach, but it has been used like this for years now.
Maybe we should come up with an easy mapping from the current system to the dwciri namespace, without harassing users.

**Comment by tucotuco** [comment]
> Does anyone know if this would work with IPT? As far as I know there's no indication of namespace in the mapping panel?

Yes. Have a look at the Audubon Media Description Extension (https://tools.gbif.org/dwca-validator/extension.do?id=http://rs.tdwg.org/ac/terms/Multimedia), which uses terms with the same label but different namespace. In the IPT both terms are presented for mapping.

**Comment by AbbyBenson** [comment]
At the 2021-09-20 meeting of the OBIS QC Task Group we determined that making this change would result in a significant amount of work for the OBIS Secretariat and some of the OBIS Nodes to modify R packages, data processing pipelines, and documentation. Knowing that the [standard will be evolving](https://vimeo.com/564600741) in the not to distance future we have decided to wait for this update to occur before making any changes to the systems and models we are currently using.
