### ISSUE TITLE
review parentMeasurementID for OBIS eMOF

### ISSUE THREAD

**Issue by ymgan** [iobis/obis-issues#198]
@tucotuco invited us to review the term [parentMeasurementID](https://github.com/tdwg/dwc/issues/362) for OBIS eMOF extension (https://github.com/iobis/obis-issues/issues/196#issuecomment-900506083). Hence, this issue is created to collect everyone's opinion in this.

Please feel free to add your use case(s) here and let us know what you think about having this term in eMOF.

### Potential use case for Southern Ocean Diet and Energetic database

Mentioned by @antonarctica in previous OBIS data QC task team meeting

On ships for a whole catch (or a fraction) the volume of the catch will be determined (l or m3). A subset of that catch will then be used for individual measurements or of a subset. Often they will try to use these individual measurements to link back to the total.
So they might determine the volume of the whole catch (of krill as an example) then take 10 percent of that volume and do length measurements on those. These values will be used to estimate those of the whole catch (number of animals/ length frequency…)

### Related GitHub issues with potential use case

Store standard deviation and other statistical qualifiers:  https://github.com/iobis/env-data/issues/20
How to deal with datasets which have both length measurements and abundances?:https://github.com/iobis/env-data/issues/10

@rubenpp7 - please feel free to include potential use case from Eurobis here
@pieterprovoost - please feel free to include your opinion/consideration at the implementation level as well, how easy/difficult it is to implement, how much this will impact OBIS portal and users etc.

Thank you so much!!

**Comment by ymgan** [comment]
use case from Anton and https://github.com/iobis/env-data/issues/10 added to use case for [GBIF new data model](https://docs.google.com/document/d/1rpxveUfN9MCdo38mJR0LaWerMo5Je0oL6p1Yym5gxH4/edit#heading=h.s91o7eupvwg7)

**Comment by AbbyBenson** [comment]
Would it be possible to discuss this one a bit at our meeting this week if we are meeting? At TDWG a few folks from France were really keen to get parentMeasurementID added to EMoF. As I understand from Pieter there are no technical limitations from the OBIS side to this but we would need to vet this with the OBIS nodes. I'm curious what we need to do to come to final decision.

**Comment by ymgan** [comment]
I have brought this up in a number of meetings. Ruben said that he has use case for statistical qualifiers but he has no time to look at that. It was previously mentioned that we don't have a particular need in this so we are not particularly pushing for it. 

Our agenda is already pretty packed and it is not within the scope of data quality team, but I understand that it is a good avenue to discuss it. I will schedule it in, but let's keep the discussion short and concise.

**Comment by ymgan** [comment]
Responded. Closing issue 

https://github.com/tdwg/dwc/issues/362#issuecomment-1412540791
