### ISSUE TITLE
obis mapper filters documentation

### ISSUE THREAD

**Issue by ymgan** [iobis/obis-issues#201]
Having documentation (or link to documentation) for the filters in OBIS mapper would be really helpful! For example, under `Options` it is unclear why certain records are dropped, what is HAB species ... 

```
Options:

- only dropped records
- only Red List species
- only HAB species 
```

Thanks a lot!!

**Comment by pieterprovoost** [comment]
Thanks @ymgan, would you mind logging this at https://github.com/iobis/mapper/issues?
