### ISSUE TITLE
Issue with old records 

### ISSUE THREAD

**Issue by PedroAros-ESP-OBIS** [iobis/obis-issues#210]
We would appreciate it if you could assist us with the next issue. We have received a data set from a museum collection, which most of them are old records. Hence, we have two situations with regard to the data information, some records do not present dates and others lack dates, coordinates and locality. 

We wonder what would be the best practice to proceed with this kind of situation?. Should we delete these rows of the records or there is another way to solve this problem?.  

Many thanks in advance

**Comment by pieterprovoost** [comment]
@PedroAros-ESP-OBIS No need to delete these records, just leave the fields blank if the information is not available. Note that records without coordinates will not be visible by default in OBIS ("dropped"), but there may still be value in these records so please do not leave them out.
