### ISSUE TITLE
Adding an associated organization

### ISSUE THREAD

**Issue by Branferza** [iobis/obis-issues#211]
We have problems adding a new and first organization to the ESP-OBIS IPT. Specifically, we are trying to add this new organization https://www.gbif.org/publisher/83685206-0bee-407b-8ed1-ac70087acf3f. 

Our problem is finding the Organization's shared token. We try to request it through the IPT but they let us know that they did not receive any request. Then they sent us a code, an organizational password that they received when was created their rehistry with GBIF, however, they were not sure if it was the token. Unfortunately, it did not work.

Reading we find out that the shared token is in the registry https://registry.gbif.org/organization/83685206-0bee-407b-8ed1-ac70087acf3f. However, we were unable to find the token here.

We request advice in this matter please.

**Comment by pieterprovoost** [comment]
@Branferza The token should be included in the email received by the organization from GBIF after endorsement as a publisher. If that doesn't work I suggest you contact <helpdesk@gbif.org>, maybe they can reset it.

**Comment by Branferza** [comment]
Thanks!
