### ISSUE TITLE
suggest to include authorship in scientificName in OBIS recommendation

### ISSUE THREAD

**Issue by ymgan** [iobis/obis-issues#212]
I would like to suggest an amendment for current recommendation on `scientificName` on this page https://manual.obis.org/darwin_core.html#taxonomy-and-identification:

> We recommend to not include authorship in scientificName, and only use scientificNameAuthorship for that purpose.

I would like to suggest to explicitly **include** authorship in the `scientificName` with the following reasons:

1. Follow the Darwin Core standard. The definition explicitly says

> The full scientific name, with authorship and date information if known.

2. The reviewers of data paper from our data providers are **consistently** requesting us to include authorship in the `scientificName` when we submitted the data based on OBIS recommendation (i.e. excluding authorship in `scientificName` and having them in `scientificNameAuthorship`). This has happened numerous times. This recommendation is creating more work for us and our data providers. 

3. I also have some data providers with marine data who read Darwin Core Quick Reference Guide (https://dwc.tdwg.org/terms/#dwc:scientificName), providing data based the guide where they explicitly include authorship in the scientificName field according to the definition. I don't have a good argument to tell them not to follow the standard and opt for OBIS recommendation.

**Comment by pieterprovoost** [comment]
Thanks @ymgan, I'll check if there are any implications for data processing and then see if there are any objections from the SG before changing the recommendation.

**Comment by JohnNichollsTCD** [comment]
This looks like a sensible suggestion, but I would like to clarify that it will still be acceptable for us to use scientificNameAuthorship for author details if needed.

**Comment by pieterprovoost** [comment]
@JohnNichollsTCD Yes absolutely, it's fine to keep using `scientificNameAuthorship` but it's preferred to include the authorship in `scientificName` as well.

**Comment by JohnNichollsTCD** [comment]
Thanks @pieterprovoost!

**Comment by EliLawrence** [comment]
I've updated the recommendation for scientificName on the [Manual](https://manual.obis.org/darwin_core.html#taxonomy-and-identification) to include authorship so I will close this issue now
