### ISSUE TITLE
OBIS node pages

### ISSUE THREAD

**Issue by skybristol** [iobis/obis-issues#23]
I notice that individual data providers have "pages" to visit.

I.e., http://beta.iobis.org/explore/#/institute/12751

But the OBIS nodes from the map on the front page don't link to a "report" for the node. I would recommend having those pages from the exploration portal as well. It would be useful to see the data providers that OBIS nodes represent and the datasets they have provided in a live summary report.

**Comment by wardappeltans** [comment]
OBIS node pages are added, e.g. http://iobis.org/explore/#/node/3

This file is a mock-up of how the OBIS node page could look like:
[OBIS-node-page.pptx](https://github.com/iobis/obis-issues/files/648696/OBIS-node-page.pptx)

To be decided upon at SG-OBIS-6.
