### ISSUE TITLE
Change WoRMS ID to AphiaID everywhere

### ISSUE THREAD

**Issue by bart-v** [iobis/obis-issues#24]
This is the standard used on marinespecies.org, please use that.

**Comment by pieterprovoost** [comment]
fixed

**Comment by bart-v** [comment]
Still worms_id here
http://download.iobis.org/?scientificname=Solea%20solea

**Comment by pieterprovoost** [comment]
The download toolbox is deprecated (still need to take it offline), but in the [mapper downloads](http://iobis.org/mapper2/?taxonid=511164) we still have `worms_id`. Will try to fix for next harvest. I expect to fully move to AphiaIDs for taxa later this year.
