### ISSUE TITLE
Occurrences section on dataset pages showing "No Data Available"

### ISSUE THREAD

**Issue by skybristol** [iobis/obis-issues#25]
The Occurrences section on all of the dataset pages I've looked at have a gray box section that shows "No Data Available" (e.g., http://beta.iobis.org/explore/#/resource/721). I'm not sure what is supposed to go here, but I'd love to take a look.

**Comment by JohnOPI** [comment]
Same issue: When searching, for example, the "HMAP Dataset 04: World Whaling" data set, Occurrence display is simply a grey area with "No Data Available" displayed.

**Comment by pieterprovoost** [comment]
Thanks for reporting. There seems to be an issue with the current harvest, I'll look into it.

**Comment by pieterprovoost** [comment]
fixed
