### ISSUE TITLE
Common name search is inconsistent

### ISSUE THREAD

**Issue by JohnOPI** [iobis/obis-issues#29]
A search for "whale" does not include "Sperm whale";
A search for "Sperm whale" includes three separate and different examples of "Sperm whale"

**This issue links with issue #19**

**Comment by bart-v** [comment]
This is really a WoRMS issue:
http://www.marinespecies.org/aphia.php?p=taxlist&searchpar=1&tComp=begins&tName=Sperm+whale&adv=1

I propose we remove the common name from the family (Physeteridae) and the synonym (Physeter catodon Linnaeus, 1758)

OK?

**Comment by wardappeltans** [comment]
@bart-v yes that sounds like the solution.

**Comment by JohnOPI** [comment]
The issue persists in the general "whale" search. Still no "Sperm whale" appearing in the list. 

The previous solution sounds like exactly the way to go for the 3 "Sperm whale" entries.

**Comment by bart-v** [comment]
OK, the "sperm whale" issue is now fixed in WoRMS, should be fixed in OBIS after next harvest.

**Comment by JohnOPI** [comment]
Thanks Bart - that's great!

**Comment by pieterprovoost** [comment]
I have added the scientific name to the suggestions, this should clear up some confusion.
