### ISSUE TITLE
Library only shows some 2016 entries

### ISSUE THREAD

**Issue by JohnOPI** [iobis/obis-issues#30]
Is there access to earlier entries? Perhaps a scroll or tab access by year?

**Comment by wardappeltans** [comment]
you have to click on the year in the bar chart.

**Comment by JohnOPI** [comment]
Works really well - is it possible to add a note to let people know to click on the graph? This issue was raised by an external data user without any previous knowledge of OBIS.

**Comment by pieterprovoost** [comment]
fixed
