### ISSUE TITLE
Are library entries regularly reviewed?

### ISSUE THREAD

**Issue by JohnOPI** [iobis/obis-issues#31]
Trawling through the library entries, I found one that was clearly faulty. When I checked the download and info, there was no such entry available.

**76	???????, ?.?.; ?????, ?.?. (2004). Принципы построения распределенных информационных систем на основе протокола Z39. 50: проекты и решения. [S.n.]: [s.l.]. ISBN 5-9554-0017-6. 57 pp.**

Perhaps this is an isolated incident, but what check is made on entries?

**Comment by wardappeltans** [comment]
good catch. it appears to be removed from the VLIZ library catalogue. the OBIS page is refreshed every week so this record will be removed.

**Comment by JohnOPI** [comment]
Thank you Ward - it is really difficult to keep on top of these types of issues.
