### ISSUE TITLE
add download button for datasets

### ISSUE THREAD

**Issue by wardappeltans** [iobis/obis-issues#36]
add download button next to records on the resources page, eg. http://beta.iobis.org/explore/#/resource/1545

**Comment by pieterprovoost** [comment]
provided CSV and DwC-A download

**Comment by wardappeltans** [comment]
Waarom hier geen DwC-A?
http://beta.iobis.org/explore/#/dataset/4057





Ward Appeltans
Project Manager OBIS, GOOS Biology & Ecosystems, IOC Capacity Development
Intergovernmental Oceanographic Commission of UNESCO
IOC Project Office for IODE – Wandelaarkaai 7/61 - 8400 Oostende - Belgium | +32 59 340176 | @WrdAppltns | w.appeltans@unesco.org<mailto:w.appeltans@unesco.org>

**Comment by pieterprovoost** [comment]
Will fix.
