### ISSUE TITLE
CC license for organism images

### ISSUE THREAD

**Issue by jhammock** [iobis/obis-issues#42]
Lovely new interface! I think the EOL Pages API may be providing the images (or some of them) in your taxon pages? Fantastic! Image owner display is appreciated. Could the license also be displayed? That field should be available directly from Pages also. There are a variety of icons available (https://creativecommons.org/about/downloads/) or a text string works too, eg "CC-BY-NC"

**Comment by pieterprovoost** [comment]
Thank you, fixed.
