### ISSUE TITLE
Provide or work out a mechanism for updating institution details

### ISSUE THREAD

**Issue by skybristol** [iobis/obis-issues#46]
We don't necessarily need an online tool (but that would be nice if it could be worked out securely) to keep the information up to date on institutions (e.g., http://beta.iobis.org/explore/#/institute/5055). In addition, we might want to add a couple of other properties to the schema (without going crazy) beyond name, acronym, and description such as contact information, web links, and identifiers.

Maintaining this information in iOBIS should probably be the responsibility of the OBIS nodes where we assign a primary OBIS node as the responsible party for a given set of organization records, recognizing that there will be cases where multiple nodes will be submitting datasets tied to the same institutions. This could facilitate an authentication/authorization scheme for an online app to maintain institution information and maybe other details for the nodes.

Ideally, we might use something like Ringgold institution identifiers to help disambiguate and uniquely identify institutions to a larger authority system. Ringgold is the source that ORCID is using for institution affiliations. Other activities I've been involved in have used identifiers from Vivo or a few other sources that provide an API where further details can be retrieved. There isn't a perfect solution yet, but we should make room in the schema for one or more identifiers for each institution that would give us some extensibility into the future.

**Comment by pieterprovoost** [comment]
@skybristol @wardappeltans @bart-v 

We are currently using IMIS as a metadata provider. See http://www.vliz.be/en/imis?module=institute&insid=5055 and http://www.vliz.be/en/imis?module=institute&insid=5055&show=json for example. As far as I know, they do not have an interface for managing records, and changes need to be requested by e-mail. I agree that it would be better if this could be managed by the nodes.

**Comment by leenvandepitte** [comment]
Using IMIS as a metadata system should remain and there is no need to open the system to all the node managers.

The most important thing remains to inform providers & node managers that they need to provide good quality metadata through their IPTs or other ways. The system in which they do this is less important, as long as we can read it. By handling the metadata in one system (IMIS) specifically for OBIS, by a limited number of people, we can guarantee consistency in the way information is added and displayed. Notifying errors through email is the easiest and best way, we respond as quickly as possible to such messages.

**Comment by wardappeltans** [comment]
Since IMIS is no longer an option, we are currently developing a new metadata system, linked with OceanExpert. The metadata on obis.org will reflect what is provided to us in the EML metadata, so updates should be done via IPT.
