### ISSUE TITLE
Properly redirect old mapper URLs

### ISSUE THREAD

**Issue by bart-v** [iobis/obis-issues#49]
i.e. this link no longer works:
http://www.iobis.org/mapper/species_info.php?id=511164

All files under /mapper should be properly redirected, i.e.:
http://mapper.iobis.org/mapper/species_info.php?id=511164

**Comment by pieterprovoost** [comment]
Are these URLs used anywhere as such? The mapper fetches them as http://mapper.iobis.org/mapper/species_info.php?id=511164, as expected.

**Comment by bart-v** [comment]
We sometimes link to such a page.
The point is that old link should properly redirected, to prevent link rot.
It's basically one line in your .htaccess

**Comment by pieterprovoost** [comment]
Fixed, please let us know if you intend to embed these (internal) links in other applications.
