### ISSUE TITLE
Manual - training/cartodb - dead link

### ISSUE THREAD

**Issue by bart-v** [iobis/obis-issues#56]
http://www.iobis.org/manual/onlinegis/

(1) "This dataset is available at https://github.com/iobis/training/tree/master/demo/cartodb
Adding the data"

The link is dead...

(2) Another one: "The shapefile is also available here."
https://github.com/iobis/training/tree/master/demo/summaries
= 404

(3) The code and data for this section are available at https://github.com/iobis/training/tree/master/demo/qc.
= 404

**Comment by pieterprovoost** [comment]
Thanks, fixed.
