### ISSUE TITLE
large zips from http://download.iobis.org not extracting on Mac default unzip, but works with p7zip

### ISSUE THREAD

**Issue by bbest** [iobis/obis-issues#63]
Really love the speed of querying and download at http://download.iobis.org apparently enabled by ElasticSearch.

When I leave the fields blank however to download the entire OBIS database and try to extract on a Mac by double-clicking to extract using the default Archive Utility, I get the following:

![image](https://user-images.githubusercontent.com/2837257/28684925-03324af0-72bb-11e7-9f1d-8900b5a3e2ef.png)

When I try on the command line via Terminal, I get more details on the problem:

```
unzip 04feee5a9ee04578a88c2f407b36c1941e5db5ad.zip -d obis_download

Archive:  04feee5a9ee04578a88c2f407b36c1941e5db5ad.zip
   skipping: 04feee5a9ee04578a88c2f407b36c1941e5db5ad.csv  need PK compat. v4.5 (can do v2.1)
```

Apparently I need PK v4.5, which is short for creator Phil Katz of commercial [PKWare](https://www.pkware.com). Per [zip - Error trying to unzip file: "need PK compat. v6.1 (can do v4.6)" - Unix & Linux Stack Exchange](https://unix.stackexchange.com/questions/183452/error-trying-to-unzip-file-need-pk-compat-v6-1-can-do-v4-6), I installed p7zip and successfully extracted. 

```
brew install p7zip
7za x 04feee5a9ee04578a88c2f407b36c1941e5db5ad.zip

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 2266954038 bytes (2162 MiB)

Extracting archive: 04feee5a9ee04578a88c2f407b36c1941e5db5ad.zip
--
Path = 04feee5a9ee04578a88c2f407b36c1941e5db5ad.zip
Type = zip
Physical Size = 2266954038

Everything is Ok

Files: 2
Size:       40677708952
Compressed: 2266954038
```

Might have something to do with `HugeFiles=on`, since smaller zips like http://download.iobis.org/?scientificname=Pterois%20volitans work fine.

You might want to add a note for larger files about this issue, or try a different backend zip procedure.

**Comment by pieterprovoost** [comment]
Hi Ben, thanks for the feedback! The easiest way for most users is probably by installing [Keka](http://www.kekaosx.com/en/), which uses p7zip for compression. I'll add some instructions in the help section.

**Comment by bbest** [comment]
👍

**Comment by pieterprovoost** [comment]
Added macOS warning.
