### ISSUE TITLE
BasisofRecord: LivingSpecimens

### ISSUE THREAD

**Issue by wardappeltans** [iobis/obis-issues#66]
Dear EurOBIS (@Daphnisd, @leenvandepitte) and Arctic OBIS,

Below is a list of datasets from you that have LivingSpecimen as Basis of Record.  This should be changed  to HumanObservation, because LivingSpecimen should only be used for specimens that are collected and intentionally kept or cultivated in e.g. aquaria or culture collections. 

ResourceIDs: 
3196
4485
3182
4440
4405
3186
4386
3154
3149
4408
3191

I think only this dataset is correctly assigned to LivingSpecimens: 
http://iobis.org/explore/#/dataset/3541

**Comment by HoddiHelga** [comment]
Arctic OBIS have made the changes.

4485 - Distribution and diversity of sipunculan fauna in high Arctic fjords (west Svalbard)
4440 - The Ecology of the Inshore Marine Zooplankton of the Chukchi Sea near Point Barrow, Alaska
4405 - Composition and distribution of the biomass of zooplankton in the central Arctic Basin 1975, 1976, 1977
4386 - Barents Sea Zooplankton – March and May 1998 and July 1999. Day/night stratified zooplankton sampling onboard the Norwegian R/V Jan Mayen. Program ALV
4408 - Barents Sea Zooplankton – March and May 1998 and July 1999. Zooplankton sampling on board the Norwegian R/V Jan Mayen, program ALV

Regards, Hóddi

**Comment by Daphnisd** [comment]
Changed in EurOBIS database. The IPT dataset will be changed during next export (=planned before 22 september).
