### ISSUE TITLE
document vlookup for taxon matching

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/obis-issues#69]

**Comment by wardappeltans** [comment]
it's well described here: http://www.excel-user.com/2009/10/vlookup-get-value-based-on-another.html

VLOOKUP(lookup_value,table_array,col_index_num,range_lookup)

**Comment by wardappeltans** [comment]
check https://www.youtube.com/watch?v=-5-_wTEFOYc&feature=youtu.be, which is also on OTGA.
