### ISSUE TITLE
Typos in manual: 

### ISSUE THREAD

**Issue by jdpye** [iobis/obis-issues#73]
In Checking Points on Land:
Second  leafletmap() call calls `land` again instead of `land_buffer`

In the ggplot section: the `maps` R library is required but not imported/installed by this scriptset.

When verifying the obis-env functions correctly catch the dummy data entries, we don't reset the state of the dataset before attempting the next example, which creates an error. Perhaps it could be more explicit about removing the dummy values in the doc.

**Comment by pieterprovoost** [comment]
Thanks, fixed.
