### ISSUE TITLE
Abstract missing

### ISSUE THREAD

**Issue by davewatts3** [iobis/obis-issues#79]
https://portal.obis.org/dataset/e5272499-c343-4794-89e0-e78bd2f5367d
the eml abstract did not show up from the IPT at http://ogc-act.csiro.au/ipt/resource?r=in2017_t01_wov&v=1.0

**Comment by pieterprovoost** [comment]
Confirmed, this is a known bug https://github.com/iobis/obis-metaloader/issues/4
