### ISSUE TITLE
Portal Search

### ISSUE THREAD

**Issue by bajonal** [iobis/obis-issues#92]
Dataset search does not find  'OTN Inner Bay of Fundy Atlantic Salmon - Tag Release Metadata' using 'Bay of Fundy' in search.

**Comment by bajonal** [comment]
Also today Only finding 20 of 26 datasets when searching for OTN.  Though good to note, via OBIS Canada Node, by Data Providers, Ocean Tracking Network is finding all 26 including the finally updated digir sets harvested November 2018 (though posted March 2018).

**Comment by bajonal** [comment]
Original Issue appears to have been fixed...though not having full search list could be a problem if the one I am looking for is not provided in the 10 or 20 list.  Test link only listing 10 of the 20 OTN datasets...of course I know how to get the full list, just saying:)

**Comment by pieterprovoost** [comment]
For now a full list can be found here: https://test.obis.org/datasets Better search (in abstract etc) will be added later.

**Comment by bajonal** [comment]
Thats great, thanks for the info.
