### ISSUE TITLE
Organisation not updated from revised EML record

### ISSUE THREAD

**Issue by davewatts3** [iobis/obis-issues#95]
Organisations https://portal.obis.org/dataset/dc9c4c41-ec01-422f-9770-fb2061570142 not updated

Resource is at http://ogc-act.csiro.au/ipt/resource?r=seabird_atlas_southeast_australia

**Comment by pieterprovoost** [comment]
Seems to be correct in the contacts list and data providers list (ANU and CSIRO Oceans and Atmosphere), apart from the nameless _Associated Party_ which is a known bug?

<img width="460" alt="screenshot 2018-11-12 at 21 09 02" src="https://user-images.githubusercontent.com/490041/48372659-93f13280-e6bf-11e8-901c-19c59042e4e0.png">
